import assert from 'node:assert/strict';
import {compare,reach,legacy,visible,validate} from '../analyzer/demo/model.js';
const nodes=['a','b','c','d'].map(id=>({id,label:id,type:'x'}));
const edges=[['a','b'],['b','c'],['b','d'],['c','b'],['d','d']].map(([source,target],i)=>({id:'e'+i,source,target}));
assert.deepEqual([...reach(nodes,edges,'a','down')].sort(),['a','b','c','d']);
assert.deepEqual([...reach(nodes,edges,'c','up')].sort(),['a','b','c']);
const before={nodes,edges,complete:true,scope:'x'},after={...before,nodes:nodes.slice(0,3),edges:edges.filter(e=>e.source!=='d'&&e.target!=='d')};
assert.equal(compare(before,after).nodes.get('d'),'removed');assert.equal(compare({...before,complete:false},after).comparable,false);
assert.equal(visible(before,{types:new Set()}).nodes.length,0);
const flowNodes=[...nodes.map(n=>({...n,type:n.id==='b'?'needle':'other'})),{id:'e',label:'e',type:'other'},{id:'f',label:'f',type:'other'},{id:'g',label:'g',type:'other'}];
const flowEdges=[...edges,{id:'e5',source:'e',target:'f'}];
const flow=visible({nodes:flowNodes,edges:flowEdges},{types:new Set(['other'])});
assert.deepEqual(flow.nodes.map(n=>n.id),['a','c','d','e','f','g']);
assert.deepEqual(flow.edges.filter(e=>e.collapsed).map(e=>[e.source,e.target,e.via]),[['a','c',['b']],['a','d',['b']],['c','c',['b']],['c','d',['b']]]);
assert.ok(flow.edges.some(e=>e.source==='d'&&e.target==='d'&&!e.collapsed));
assert.ok(flow.edges.some(e=>e.source==='e'&&e.target==='f'&&!e.collapsed));
assert.ok(!flow.edges.some(e=>e.source==='d'&&e.target==='a'));
const bySearch=visible({nodes:flowNodes,edges:flowEdges},{types:new Set(['other']),query:'e'});
assert.deepEqual([...bySearch.matched],['e']);
assert.deepEqual(bySearch.nodes.map(n=>n.id),['e','f']);
assert.deepEqual(bySearch.edges.map(e=>e.id),['e5']);
const focused=visible({nodes:flowNodes,edges:flowEdges},{types:new Set(['needle']),focus:'c',direction:'up'});
assert.deepEqual(focused.nodes.map(n=>n.id),['b']);
assert.deepEqual(focused.edges.map(e=>[e.source,e.target,e.via]),[['b','b',['c']]]);
const linearNodes=['source','middle','target'].map((id,i)=>({id,label:id,type:i===1?'hidden':'shown'}));
const linearEdges=[{id:'first',source:'source',target:'middle'},{id:'next',source:'middle',target:'target'}];
const contracted=visible({nodes:linearNodes,edges:linearEdges},{types:new Set(['shown'])});
assert.deepEqual(contracted.nodes.map(n=>n.id),['source','target']);
assert.deepEqual(contracted.edges.map(e=>[e.source,e.target,e.via,e.sourceEdges]),[['source','target',['middle'],['first','next']]]);
assert.deepEqual(visible({nodes:linearNodes,edges:linearEdges},{types:new Set(['shown','hidden'])}).edges,linearEdges);
const imp=legacy([{key:'x',name:'X'}],[{key:'a',group:'x ',title:'A'}],[{from:'a',to:'a'},{from:'a',to:'a'}]);assert.equal(imp.project.snapshots[0].edges.length,1);assert.equal(imp.warnings.length,2);
assert.throws(()=>validate({schemaVersion:1,snapshots:[{id:'x',capturedAt:'bad',nodes:[],edges:[]}]}));
console.log('Domain checks passed: branches, cycles, self-loop, partial snapshots, filters, legacy adapter.');
